---
# Title: OTOBO Ticket system
#
# Authtor: bitfinity-nl
# File: tasks/main.yml
#
# Description:
#   OTOBO is the new free Open Source ticket system 
#   with strong functionality AND a great look.

- name: "Type:elasticsearch, For OS: Ubuntu 20.04LTS, Arch: amd64, State: Enabled"
  import_tasks: traditional/ubt-2004-amd64-elasticsearch.yml
  when:
    - otobo_install_type == 'traditional'
    - ansible_distribution_version == '20.04'
    - ansible_architecture == 'x86_64'
    #- ansible_memtotal_mb >= "7961"

- name: "Type:otobo, For OS: Ubuntu 20.04LTS, Arch: amd64, State: Enabled"
  import_tasks: traditional/ubt-2004-amd64-otobo.yml
  when:
    - otobo_install_type == 'traditional'
    - ansible_distribution_version == '20.04'
    - ansible_architecture == 'x86_64'
    
- name: "Type:LDAPAD, For OS: Ubuntu 20.04LTS, Arch: amd64, State: Enabled"
  import_tasks: traditional/ubt-2004-amd64-ldap.yml
  when:
    - otobo_install_type == 'traditional'
    - ansible_distribution_version == '20.04'
    - ansible_architecture == 'x86_64'
    - otobo_ad_status == 'enabled'

- name: "Type:Docker, For OS: Ubuntu 20.04LTS, Arch: amd64, State: Enabled"
  import_tasks: docker/dock-ubt-2004-amd64-otobo.yml
  when:
    - otobo_install_type == 'docker'
    - ansible_distribution_version == '20.04'
    - ansible_architecture == 'x86_64'
