---
# Title: OTOBO Ticket system
#
# Authtor: bitfinity-nl
# File: tasks/main.yml
#
# Description:
#   OTOBO is the new free Open Source ticket system 
#   with strong functionality AND a great look.


- name: "Type:elasticsearch, For OS: Ubuntu 20.04LTS, Arch: amd64, State: Enabled"
  import_tasks: ubt-2004-amd64-elasticsearch.yml
  when:
    - ansible_distribution_version == '20.04'
    - ansible_architecture == 'x86_64'

#- name: "Type:otobo, For OS: Ubuntu 20.04LTS, Arch: amd64, State: Enabled"
#  import_tasks: ubt-2004-amd64-otobo.yml
#  when:
#    - ansible_distribution_version == '20.04'
#    - ansible_architecture == 'x86_64'

#- name: "Type:mariadb, For OS: Ubuntu 20.04LTS, Arch: amd64, State: Enabled"
#  import_tasks: ubt-2004-amd64-mariadb.yml
#  when:
#    - ansible_distribution_version == '20.04'
#    - ansible_architecture == 'x86_64'

#- name: "Type:LDAPAD, For OS: Ubuntu 20.04LTS, Arch: amd64, State: Enabled"
#  import_tasks: ubt-2004-amd64-ldap.yml
#  when:
#    - ansible_distribution_version == '20.04'
#    - ansible_architecture == 'x86_64'
