  
---
# Title: OTOBO Ticket system
#
# Authtor: bitfinity-nl
# File: tasks/ubt-2004-amd64-ldap.yml
#
# Description:
#   OTOBO is the new free Open Source ticket system 
#   with strong functionality AND a great look.
#
# Source(s):
#   - https://doc.otobo.org/manual/admin/stable/en/content/users-groups-roles/agents.html
#

- name: "Add LDAP/AD configuration"
  blockinfile:
    path: /opt/otobo/Kernel/Config.pm
    marker: "    #<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertafter: ".*#*Self.*{CheckMXRecord} = 0;"
    block: |2
          $Self->{AuthModule} = 'Kernel::System::Auth::LDAP';
          $Self->{'AuthModule::LDAP::Host'} = '{{ otobo_ad_dc }}';
          $Self->{'AuthModule::LDAP::BaseDN'} = '{{ otobo_ad_basedn }}';
          $Self->{'AuthModule::LDAP::UID'} = '{{ otobo_ad_uid }}';

          # Bind DN to LDAP-Active Directory for searching accounts.
          $Self->{'AuthSyncModule::LDAP::SearchUserDN'} = '{{ otobo_ad_searchuserdn }}';
          $Self->{'AuthSyncModule::LDAP::SearchUserPw'} = '{{ otobo_ad_searchuserpw }}';

- name: "Add LDAP Active Directory administrative user to otobo"
  raw: sudo su - otobo -c "/opt/otobo/bin/otobo.Console.pl Admin::User::Add --user-name {{ otobo_ad_account }} --first-name {{ otobo_ad_firstname }} --last-name {{ otobo_ad_lastname }} --email-address {{ otobo_ad_email }} --quiet"
  ignore_errors: yes

- name: "Add agent adm_otobo to group admin/stats/users with rw permissions"
  raw: sudo su - otobo -c "/opt/otobo/bin/otobo.Console.pl Admin::Group::UserLink --user-name {{ otobo_ad_account }} --group-name {{ item }} --permission rw"
  with_items:
    - admin
    - stats
    - users
