---

- name: "Start Deamons & Cron"
  raw: "{{ item }}"
  with_items:
    -  sudo su - otobo -c "/opt/otobo/bin/otobo.Daemon.pl start"
    -  sudo su - otobo -c "/opt/otobo/bin/Cron.sh start"

- name: "Reconfigure default value for SystemID in /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm"
  replace:
     path: /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm
     regexp: \$Self->{'SystemID'} =  '10';
     replace: $Self->{'SystemID'} =  '{{ otobo_systemid }}';

- name: "Reconfigure default value for SystemID in /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm"
  replace:
     path: /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm
     regexp: \$Self->{'HttpType'} =  'https';
     replace: $Self->{'HttpType'} =  '{{ otobo_httptype }}';
     
- name: "Reconfigure default value AdminEmail in /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm"
  replace:
     path: /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm
     regexp: \$Self->{'AdminEmail'} =  'support@<OTOBO_CONFIG_FQDN>';
     replace: $Self->{'AdminEmail'} =  '{{ otobo_adminemail }}';

- name: "Reconfigure default value AdminEmail in /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm"
  replace:
     path: /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm
     regexp: \$Self->{'Organization'} =  'Example Company';
     replace: $Self->{'Organization'} =  '{{ otobo_organization }}';
