---
# Title: OTOBO Ticket system
#
# Authtor: bitfinity-nl
# File: tasks/ubt-2004-amd64-otobo-installer.yml
#
# Description:
#   OTOBO is the new free Open Source ticket system 
#   with strong functionality AND a great look.

- name: "Generate /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm"
  raw: sudo su - otobo -c "/opt/otobo/bin/otobo.Console.pl Maint::Config::Rebuild" 
  ignore_errors: yes
    
- name: "Reconfigure default value for SystemID in /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm"
  replace:
     path: /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm
     regexp: \$Self->{'SystemID'} =  '10';
     replace: $Self->{'SystemID'} =  '{{ otobo_self_systemid }}';

- name: "Reconfigure default value for HttpType in /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm"
  replace:
     path: /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm
     regexp: \$Self->{'HttpType'} =  'https';
     replace: $Self->{'HttpType'} =  '{{ otobo_self_httptype }}';
     
- name: "Reconfigure default value AdminEmail in /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm"
  replace:
     path: /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm
     regexp: \$Self->{'AdminEmail'} =  'support@<OTOBO_CONFIG_FQDN>';
     replace: $Self->{'AdminEmail'} =  '{{ otobo_self_adminemail }}';

- name: "Reconfigure default value AdminEmail in /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm"
  replace:
     path: /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm
     regexp: \$Self->{'Organization'} =  'Example Company';
     replace: $Self->{'Organization'} =  '{{ otobo_self_organization }}';

- name: "Reconfigure default value Securemode in /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm"
  replace:
     path: /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm
     regexp: \$Self->{'SecureMode'} =  '0';
     replace: $Self->{'SecureMode'} =  '{{ otobo_self_securemode }}';


#-- Installer - Authentication --
- name: "Reconfigure default value SendmailModule in /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm"
  replace:
     path: /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm
     regexp: \$Self->{'SendmailModule'} =  'Kernel::System::Email::Sendmail';
     replace: $Self->{'SendmailModule'} =  'Kernel::System::Email::SMTP';

- name: "(WIP) Reconfigure default value SendmailModule AuthPassword in /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm"
  replace:
     path: /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm
     regexp: \$Self->{'SendmailModule::AuthPassword'} =  'MailserverPassword';
     replace: $Self->{'SendmailModule::AuthPassword'} =  'MailserverPassword';

- name: "(WIP) Reconfigure default value SendmailModule AuthUser in /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm"
  replace:
     path: /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm
     regexp: \$Self->{'SendmailModule::AuthUser'} =  'MailserverLogin';
     replace: $Self->{'SendmailModule::AuthUser'} =  'MailserverLogin';
     
- name: "Reconfigure default value SendmailModule CMD in /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm"
  replace:
     path: /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm
     regexp: \$Self->{'SendmailModule::CMD'} =  '/usr/sbin/sendmail -i -f';
     replace: $Self->{'SendmailModule::CMD'} =  '/usr/sbin/sendmail -i -f';

- name: "(WIP)Reconfigure default value SendmailModule Port in /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm"
  replace:
     path: /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm
     regexp: \$Self->{'SendmailModule::Port'} =  '25';
     replace: $Self->{'SendmailModule::Port'} =  '25';
     
- name: "Reconfigure default value SendmailModule Host in /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm"
  replace:
     path: /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm
     regexp: \$Self->{'SendmailModule::Host'} =  'mail.example.com';
     replace: $Self->{'SendmailModule::Host'} =  'mail.vissersolie.nl';     

#--


- name: "Set password for root@localhost"
  raw: sudo su - otobo -c "/opt/otobo/bin/otobo.Console.pl Admin::User::SetPassword root@localhost {{ otobo_root_password }}" 
  ignore_errors: yes
  
- name: "Start Deamons & Cron"
  raw: "{{ item }}"
  with_items:
    -  sudo su - otobo -c "/opt/otobo/bin/otobo.Daemon.pl start"
    -  sudo su - otobo -c "/opt/otobo/bin/Cron.sh start"
