---
# Title: OTOBO Ticket system
#
# Authtor: bitfinity-nl
# File: tasks/traditional/ubt-2004-amd64-otobo-10-1.yml
#
# Description:
#   OTOBO is the new free Open Source ticket system 
#   with strong functionality AND a great look.

- name: "Install packages"
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - unzip
    - apache2 
    - libapache2-mod-perl2
    # Additional Perl modules
    - libdatetime-perl
    - libcrypt-eksblowfish-perl 
    - libcrypt-ssleay-perl
    - libgd-graph-perl
    - libapache-dbi-perl
    - libsoap-lite-perl 
    - libarchive-zip-perl 
    - libgd-text-perl 
    - libnet-dns-perl 
    - libpdf-api2-perl
    - libauthen-ntlm-perl 
    - libdbd-odbc-perl 
    - libjson-xs-perl
    - libyaml-libyaml-perl 
    - libxml-libxml-perl 
    - libencode-hanextra-perl 
    - libxml-libxslt-perl 
    - libpdf-api2-simple-perl 
    - libmail-imapclient-perl 
    - libtemplate-perl 
    - libtext-csv-xs-perl 
    - libdbd-pg-perl
    - libapache2-mod-perl2
    - libtemplate-perl
    - libnet-dns-perl 
    - libnet-ldap-perl 
    - libio-socket-ssl-perl
    - libdbd-mysql-perl
    - libmoo-perl
    # For Otobo 10.1
    - libcgi-psgi-perl
    - libdbix-connector-perl
    - libfile-chmod-perl
    - liblist-allutils-perl
    - libpath-class-perl
    - libtext-trim-perl
    - libplack-perl
    - libplack-middleware-header-perl
    - libplack-middleware-reverseproxy-perl
    - libconst-fast-perl

- name: "Enable Apache modules"
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - perl
    - headers
    - version
    - deflate
    - filter
    - proxy
    - proxy_http
    - proxy_wstunnel
    - ssl
  notify: restart_apache2

- name: "Create directory structure"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ otobo_dest }}"

#- name: "Dowload sources from GIT"
#  git:
#    repo: https://github.com/OTRS/otrs.git
#    dest: "/opt/otrs"

- name: "Download sources from OTOBO"
  unarchive: 
    src: "{{ otobo_download_url }}"
    dest: "{{ otobo_dest }}"
    extra_opts: [--strip-components=1]
    remote_src: yes

- name: "Type:mariadb, For OS: Ubuntu 20.04LTS, Arch: amd64, State: Enabled"
  import_tasks: ubt-2004-amd64-mariadb.yml

- name: "Create local group otobo for service account otobo user(s)"
  group:
    name: otobo
    state: present

- name: "Create local service account otobo and to security group otobo, www-data"
  user:
    name: otobo
    home: /opt/otobo
    group: otobo
    groups: www-data
    system: yes

- name: "Check Perl modules"
  command: /opt/otobo/bin/otobo.CheckModules.pl -list

- name: "Transfer configuration template"
  template:
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'Config.pm.dist.j2', dest: '/opt/otobo/Kernel/Config.pm' }

- name: "Set OTOBO file permissions"
#  shell: /opt/otobo/bin/otobo.SetPermissions.pl --web-group=www-data
  shell: /opt/otobo/bin/otobo.SetPermissions.pl

- name: "Create symlink from {{ otobo_dest }} to /opt/otobo"
  file:
    src: /opt/otobo/scripts/apache2-httpd.include.conf
    dest: /etc/apache2/sites-enabled/zzz_otobo.conf
    state: link
  notify: restart_apache2

- name: "Configure Apache with and without SSL"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'apache2-httpd-vhost-80.include.conf.j2', dest: '/etc/apache2/sites-available/zzz_otobo-80.conf' }
    - { src: 'apache2-httpd-vhost-443.include.conf.j2', dest: '/etc/apache2/sites-available/zzz_otobo-443.conf' }
    - { src: '.htaccess.j2', dest: '/var/www/html/.htaccess'}
  notify: restart_apache2

- name: "Configure /etc/apache2/apache2.conf to use .htaccess"
  blockinfile:
    path: /etc/apache2/apache2.conf
    marker: "{mark}"
    marker_begin: "<Directory /var/www/>"
    marker_end: "</Directory>"
    block: |-
              Options Indexes FollowSymLinks
              AllowOverride All
              Require all granted
    state: present
    backup: yes

- name: "Enable zzz_otobo-80.conf and zzz_otobo-443.conf"
  command: a2ensite zzz_otobo-80.conf zzz_otobo-443.conf
  notify:
    - restart_apache2

- name: "Configure UFW"
  ufw:
    rule: allow
    name: 'Apache Full'

- name: "Check if configuration file /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm exists"
  stat:
    path: /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm
  register: result_zzzaauto

- name: "Display if configuration file /opt/otobo/Kernel/Config/Files/ZZZAAuto.pm exists"
  debug:
    msg: "{{ result_zzzaauto.stat.exists }}"

#- name: "Run the installer.pl playbook when ZZZAAuto.pm does not exists"
#  import_tasks: ubt-2004-amd64-otobo-installer.yml
#  when: result_zzzaauto.stat.exists == false

- name: "Copy /opt/otobo/var/cron/*.dist to /opt/otobo/var/cron/ without .dist"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
  with_items:
    - { src: '/opt/otobo/var/cron/otobo_daemon.dist', dest: '/opt/otobo/var/cron/otobo.daemon'}
    - { src: '/opt/otobo/var/cron/aaa_base.dist', dest: '/opt/otobo/var/cron/aaa_base'}

- name: "Create directory/opt/otobo/var/tmp/"
  file:
    path: /opt/otobo/var/tmp/ 
    state: directory
    owner: otobo
    group: www-data
    mode: 0775

- name: "Start Deamons & Cron"
  raw: "{{ item }}"
  with_items:
    -  sudo su - otobo -c "/opt/otobo/bin/otobo.Daemon.pl start"
    -  sudo su - otobo -c "/opt/otobo/bin/Cron.sh start"
