---
# Title: Docker version of OTOBO
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/docker/dock-ubt-2004-amd64-otobo.yml
#
# Description:
#   This taskfile contains the installation tasks
#   of OTOBO via Docker. 
#
# Sources:
#   - https://doc.otobo.org/manual/installation/10.1/en/content/installation-docker.html
#

- name: "Install Docker requirements via APT"
  apt:
    pkg:
    - git
    - docker
    - docker-compose
 
- name: "Enable and start systemd service docker"
  systemd:
    enabled: yes
    state: started
    daemon_reload: yes
    name: docker
  
- name: "Clone the otobo-docker repo" 
  ansible.builtin.git:
    repo: 'https://github.com/RotherOSS/otobo-docker.git'
    dest: /opt/otobo-docker
    #single_branch: yes
    version: "{{ otobo_dock_branch }}"
    
- name: "Copy /opt/otobo-docker.docker_compose_env_https to /opt/otobo-docker.env"     
  ansible.builtin.copy:
    src: /opt/otobo-docker/.docker_compose_env_https
    dest: /opt/otobo-docker/.env
    remote_src: yes 

- name: "Configure /opt/otobo-docker/.env"
  lineinfile:
    path:  /opt/otobo-docker/.env
    search_string: "{{ item.find }}"
    line: "{{ item.replace }}"
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ otobo_doc_env }}"
    
